Xima\ICalBundle\Entity\Component\Event:
  type: mappedSuperclass
  id:
    id:
      column: id
      type: integer
      generator:
        strategy: AUTO
  fields:
    uniqueId:
      column: unique_id
      type: string
    dtStart:
      column: dt_start
      type: datetime
    dtEnd:
      column: dt_end
      type: datetime
    dateFrom:
      column: date_from
      type: date
      nullable: false
    timeFrom:
      column: time_from
      type: time
    dateTo:
      column: date_to
      type: date
      nullable: false
    timeTo:
      column: time_to
      type: time
    duration:
      type: dateinterval
      nullable: true
    noTime:
      column: no_time
      type: boolean
    summary:
      type: string
      nullable: true
    url:
      type: string
      nullable: true
    location:
      type: string
      nullable: true
    locationTitle:
      column: location_title
      type: string
      nullable: true
    locationGeo:
      column: location_geo
      type: string
      nullable: true
    summary:
      type: string
      nullable: true
    organizer:
      type: string
      nullable: true
    transparency:
      type: string
      nullable: true
    useTimezone:
      column: use_timezone
      type: boolean
    sequence:
      type: integer
    description:
      type: string
      nullable: true
    status:
      type: string
      nullable: true
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modified:
      type: datetime
      gedmo:
        timestampable:
          on: update
    useUtc:
      column: use_utc
      type: boolean
    cancelled:
      type: boolean
      nullable: true
    exDates:
      type: json
      nullable: true
  oneToOne:
    recurrenceRule:
      targetEntity: \Xima\ICalBundle\Entity\Property\Event\RecurrenceRule
      cascade: ["all"]
      joinColumn:
        name: recurrence_rule_id
        referencedColumnName: id
    recurrenceId:
      targetEntity: \Xima\ICalBundle\Entity\Property\Event\RecurrenceId
      cascade: ["all"]
      orphanRemoval: true
      joinColumn:
        name: recurrence_id
        referencedColumnName: id
  lifecycleCallbacks:
    postLoad: [ postLoad ]
