Xima\ICalBundle\Entity\Property\Event\RecurrenceRule:
  type: entity
  table: recurrence_rule
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    freq:
      type: string
      length: 50
      nullable: true
    interval:
      type: integer
      nullable: true
      column: `interval`
    count:
      type: integer
      nullable: true
      column: `count`
    byMonth:
      type: array
      nullable: true
    byWeekNo:
      type: array
      nullable: true
    byYearDay:
      type: array
      nullable: true
    byMonthDay:
      type: array
      nullable: true
    byHour:
      type: array
      nullable: true
    byMinute:
      type: array
      nullable: true
    bySecond:
      type: array
      nullable: true
    until:
      column: until
      type: datetime
      nullable: true
  manyToMany:
    byDays:
      targetEntity: \Xima\ICalBundle\Entity\Property\RecurrenceRule\NthOccurrence
      cascade: ["all"]
      removeOprphans: true
      joinTable:
        name: recurrence_rule_by_day
        joinColumns:
          recurrence_rule_id:
            referencedColumnName: id
        inverseJoinColumns:
          nth_occurrence_id:
            referencedColumnName: id
            unique: true
  lifecycleCallbacks:
    postLoad: [ postLoad ]