Xima\ICalBundle\Entity\Property\Event\RecurrenceId:
  type: entity
  table: recurrence_id
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    dateTime:
          column: date_time
          type: datetime
    range:
          column: `range`
          type: string
          nullable: true
  lifecycleCallbacks:
    postLoad: [ postLoad ]